GIT_ROOT ?= $(shell git rev-parse --show-toplevel)

help:	## Show all Makefile targets.
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[33m%-30s\033[0m %s\n", $$1, $$2}'

test: unit_tests integration_tests ## Run all tests

unit_tests: ## Run unit tests
	pytest tests/unit_tests

integration_tests: ## Run integration tests
	pytest tests/integration_tests